Repository werds7890/everyDayApp, pull requests merged in 2023-08, with the labels that each got.

#8 [BUG_FIX]merge
  .idea/misc.xml
  app/build.gradle
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_login_page.xml
  app/src/main/res/layout/activity_single_up_page.xml
Labels: bug

#9 [DESIGN]main_page
  app/src/main/res/drawable/github.png
  app/src/main/res/drawable/notion.png
  app/src/main/res/drawable/programmars.png
  app/src/main/res/drawable/round.xml
  app/src/main/res/drawable/slack.png
  app/src/main/res/layout/activity_main.xml
Labels: features

#10 [FEAT] : ⚙️ activity_login_page.xml 와 activity_single_up_page.xml 의 U…
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/everydayapp/LoginPage.kt
  app/src/main/res/layout/activity_login_page.xml
  app/src/main/res/layout/activity_single_up_page.xml
  app/src/main/res/values/style.xml
Labels: features

#11 Feature/detail page
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_detail.xml
Labels: features

#12 [LITTLE_FIX]main-page
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/everydayapp/MainActivity.kt
  app/src/main/java/com/example/everydayapp/TeamActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_team.xml
Labels: features

#14 UI 정리 완료
  app/src/main/res/layout/activity_detail.xml
Labels: features

#15 Splash 작업 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/everydayapp/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
Labels: features

#16 [LITTLE_FIX]게시판, 디테일페이지로 데이터넘기기 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/everydayapp/Detail.kt
  app/src/main/java/com/example/everydayapp/MainActivity.kt
  app/src/main/java/com/example/everydayapp/SplashActivity.kt
  app/src/main/java/com/example/everydayapp/WritingActivity.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_team.xml
  app/src/main/res/layout/activity_writing.xml
Labels: features

#21 TeamPage 텍스트 수정/저장 기능 추가
  app/src/main/java/com/example/everydayapp/TeamActivity.kt
  app/src/main/res/drawable/pencil.png
  app/src/main/res/drawable/save.png
  app/src/main/res/layout/activity_team.xml
Labels: features

#22 TeamPage UI 수정
  app/src/main/java/com/example/everydayapp/LoginPage.kt
  app/src/main/res/layout/activity_team.xml
Labels: UI

#25 [LITTLE_FIX]디테일페이지, 팀페이지 데이터 값 넘기기
  app/src/main/java/com/example/everydayapp/LoginPage.kt
  app/src/main/java/com/example/everydayapp/MainActivity.kt
  app/src/main/java/com/example/everydayapp/TeamActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_team.xml
Labels: features

#26 [LITTLE_FIX][DESIGN]전체페이지
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/everydayapp/Detail.kt
  app/src/main/java/com/example/everydayapp/LoginPage.kt
  app/src/main/java/com/example/everydayapp/MainActivity.kt
  app/src/main/java/com/example/everydayapp/SignUpPage.kt
  app/src/main/java/com/example/everydayapp/SplashActivity.kt
  app/src/main/res/drawable/everyday.png
  app/src/main/res/drawable/everytime.webp
  app/src/main/res/drawable/hyeon.jpg
  app/src/main/res/drawable/kitty.jpg
  app/src/main/res/drawable/leejamong.png
  app/src/main/res/drawable/orange.jpg
  app/src/main/res/drawable/pika.png
  app/src/main/res/drawable/round2.xml
  app/src/main/res/drawable/test1.jpg
  app/src/main/res/drawable/test3.jpg
  app/src/main/res/font/bitbit.ttf
  app/src/main/res/font/font.xml
  app/src/main/res/font/neo.ttf
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_login_page.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign_up_page.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_team.xml
  app/src/main/res/layout/activity_writing.xml
  app/src/main/res/values/themes.xml
Labels: features

#27 Feature/login page
  .idea/.name
  .idea/misc.xml
  .idea/sonarlint/issuestore/5/5/55d88673a66a10c18c73b1b08cac9dfeedf9794a
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/5/5/55d88673a66a10c18c73b1b08cac9dfeedf9794a
  .idea/sonarlint/securityhotspotstore/index.pb
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/everydayapp/Detail.kt
  app/src/main/java/com/example/everydayapp/LoginPage.kt
  app/src/main/java/com/example/everydayapp/MainActivity.kt
  app/src/main/java/com/example/everydayapp/SignUpPage.kt
  app/src/main/java/com/example/everydayapp/SplashActivity.kt
  app/src/main/java/com/example/everydayapp/TeamActivity.kt
  app/src/main/java/com/example/everydayapp/WritingActivity.kt
  app/src/main/res/drawable/cat.jpg
  app/src/main/res/drawable/everycustom.png
  app/src/main/res/drawable/everyday.png
  app/src/main/res/drawable/everytime.webp
  app/src/main/res/drawable/github.png
  app/src/main/res/drawable/hairbear.png
  app/src/main/res/drawable/notion.png
  app/src/main/res/drawable/pencil.png
  app/src/main/res/drawable/people.png
  app/src/main/res/drawable/pikachu.jpg
  app/src/main/res/drawable/programmars.png
  app/src/main/res/drawable/rogo.png
  app/src/main/res/drawable/round.xml
  app/src/main/res/drawable/save.png
  app/src/main/res/drawable/slack.png
  app/src/main/res/drawable/square_box.xml
  app/src/main/res/drawable/test1.jpg
  app/src/main/res/drawable/test2.jpg
  app/src/main/res/drawable/test3.jpg
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_login_page.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign_up_page.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_team.xml
  app/src/main/res/layout/activity_writing.xml
  app/src/main/res/values-en-rUS/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: features

#28 Dark theme 작업 완료
  app/src/main/res/drawable-night/everycustom.png
  app/src/main/res/drawable-night/human.png
  app/src/main/res/drawable-night/orange.jpg
  app/src/main/res/drawable/human.png
  app/src/main/res/drawable/people.png
  app/src/main/res/drawable/square_box.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_login_page.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign_up_page.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_team.xml
  app/src/main/res/layout/activity_writing.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: features

#29 [LITTLE_FIX]디테일페이지 수정기능 FIX
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/everydayapp/Detail.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_team.xml
Labels: features

#30 [LITTLE_FIX]
  app/src/main/res/layout/activity_detail.xml
Labels: features

#31 Feature/login page
  app/src/main/AndroidManifest.xml
  app/src/main/ic_main_icon-playstore.png
  app/src/main/java/com/example/everydayapp/LoginPage.kt
  app/src/main/java/com/example/everydayapp/SignUpPage.kt
  app/src/main/res/drawable/ic_main_icon_background.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_login_page.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign_up_page.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_team.xml
  app/src/main/res/layout/activity_writing.xml
  app/src/main/res/mipmap-anydpi-v26/ic_main_icon.xml
  app/src/main/res/mipmap-anydpi-v26/ic_main_icon_round.xml
  app/src/main/res/mipmap-hdpi/ic_main_icon.png
  app/src/main/res/mipmap-hdpi/ic_main_icon_foreground.png
  app/src/main/res/mipmap-hdpi/ic_main_icon_round.png
  app/src/main/res/mipmap-mdpi/ic_main_icon.png
  app/src/main/res/mipmap-mdpi/ic_main_icon_foreground.png
  app/src/main/res/mipmap-mdpi/ic_main_icon_round.png
  app/src/main/res/mipmap-xhdpi/ic_main_icon.png
  app/src/main/res/mipmap-xhdpi/ic_main_icon_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_main_icon_round.png
  app/src/main/res/mipmap-xxhdpi/ic_main_icon.png
  app/src/main/res/mipmap-xxhdpi/ic_main_icon_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_main_icon_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_main_icon.png
  app/src/main/res/mipmap-xxxhdpi/ic_main_icon_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_main_icon_round.png
  app/src/main/res/values-en-rUS/strings.xml
  app/src/main/res/values/ic_main_icon_background.xml
  app/src/main/res/values/strings.xml
Labels: features

#32 detail 페이지 정리 및 logic 정리
  app/src/main/java/com/example/everydayapp/Detail.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_team.xml
Labels: features

#37 [FEAT] : ⚙️갤러리 연동/ 이미지 변경
  app/build.gradle
  app/src/main/java/com/example/everydayapp/TeamActivity.kt
  app/src/main/res/drawable/image.png
  app/src/main/res/layout/activity_team.xml
Labels: features

#38 [FEAT]팀페이지 게시판, 디테일페이지 좌우명란 더보기 기능 추가
  app/src/main/java/com/example/everydayapp/Detail.kt
  app/src/main/java/com/example/everydayapp/TeamActivity.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_team.xml
Labels: features

#39 [UI CLEAN} Feature/detail logic4
  app/src/main/res/layout/activity_detail.xml
Labels: features

#41 detail page UI 정리 완료
  app/src/main/java/com/example/everydayapp/Detail.kt
  app/src/main/res/layout/activity_detail.xml
Labels: documentation
